### PR TITLE
Minor Update to handle Hashcode issue

### PR DESCRIPTION
**Pull request by ToonDragon**
Added rudimentary Hashcode function to all functions with an equal() command (with the exception of edit and search due to complexity)

Added a new test file to confirm compliance with the Hashcode contract

### CODE REVIEW

**Review by suriruhani — APPROVED** [review]
Necessary updates to improve object comparison accuracy. Thanks!

**Comment by ToonDragon** [comment]
Thanks for the approval, hashcode and tests for the edit and search command are still pending for now.

**Comment by suriruhani** [comment]
> Thanks for the approval, hashcode and tests for the edit and search command are still pending for now.

I will take care of `search` in my next PR, as for `edit`, I will try to implement it using the same logic you proposed for `search`.

**Comment by ToonDragon** [comment]
Sounds good!  Essentially the break down of the logic is that Predicates, like other objects, have a toString() function and each string has a hashcode() function.  So you can generate a simple hashcode for the command by taking the combined hashcode of the predicates using a function similar to predicateName.toString().hashcode().

This hash function is not perfect but it should suit the needs for the test.

**Pull request merged**
